# Generated by Django 4.1.4 on 2022-12-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="telefone",
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
